"""Render weekly digests, the master index, the survey outline, and the
GitHub Pages landing from the paper database."""

from __future__ import annotations

import json
from collections import Counter
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from presearch.database import PaperDatabase
from presearch.pillars import load_pillars


def iso_week() -> str:
    now = datetime.now(UTC)
    year, week, _ = now.isocalendar()
    return f"{year}-W{week:02d}"


def _paper_lines(records: list[dict[str, Any]], pillar: str) -> list[str]:
    papers = [record for record in records if record.get("pillar") == pillar]
    if not papers:
        return ["- (no papers in this window)\n"]
    lines: list[str] = []
    for record in papers[:15]:
        arxiv_short = record.get("arxiv_id", "").split("/abs/")[-1] or "arXiv"
        methods = ", ".join(record.get("methods", [])[:3]) or "—"
        benchmarks = ", ".join(record.get("benchmarks", [])[:4]) or "—"
        lines.append(
            f"- **{record['title']}** ([{arxiv_short}]({record.get('url', '')})) — "
            f"conf {record.get('confidence', 0):.2f} · {methods} · benchmarks: {benchmarks}"
        )
    if len(papers) > 15:
        lines.append(f"- …and {len(papers) - 15} more papers in this pillar.")
    return lines


def write_weekly(db: PaperDatabase, summary: dict[str, Any], weekly_root: Path) -> Path:
    weekly_root.mkdir(parents=True, exist_ok=True)
    path = weekly_root / f"{iso_week()}.md"
    records = summary.get("swept_records") or [
        record for record in db.load() if record.get("swept_on") == summary["swept_on"]
    ]

    lines: list[str] = [
        f"# Frontier AI Weekly — {iso_week()}",
        "",
        f"> swept {summary['fetched']} papers ({summary['new_records']} new) · "
        f"database total {summary['total_db']} · generated by P-Research",
        ">",
        "> Evidence is abstract-level (arXiv metadata). Treat claims as research signals.",
        "",
    ]
    for pillar in load_pillars(weekly_root.parent / "presearch_pillars.json"):
        lines.append(f"## {pillar}")
        lines.append("")
        lines.extend(_paper_lines(records, pillar))
        lines.append("")

    if summary["signals"]:
        lines.append("## Cross-Pillar Convergence Signals")
        lines.append("")
        for signal in summary["signals"]:
            lines.append(f"- **{signal['claim']}**")
            lines.append(f"  - spanning: {', '.join(signal['spanning_pillars'])}")
        lines.append("")

    if summary["failures"]:
        lines.append("## Degraded Pillars This Week")
        lines.append("")
        for failure in summary["failures"]:
            lines.append(f"- {failure}")
        lines.append("")

    lines.append("---")
    lines.append("_Generated by [P-Research](https://github.com/) — "
                 "human review required before external citation._")
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def write_index(db: PaperDatabase, data_root: Path) -> Path:
    records = db.load()
    stats = db.stats()
    by_pillar = {pillar: [] for pillar in load_pillars(data_root / "presearch_pillars.json")}
    for record in records:
        if record.get("pillar") in by_pillar:
            by_pillar[record["pillar"]].append(record)

    lines: list[str] = [
        "# P-Research Index",
        "",
        f"- Total papers: **{stats['total_papers']}** · "
        f"full-text verified: **{stats['verified_papers']}**",
        f"- Last sweep: {stats['newest_swept_on'] or 'never'}",
        f"- Top methods: {', '.join(f'{k} ({v})' for k, v in list(stats['top_methods'].items())[:8])}",
        "",
    ]
    for pillar, pillar_records in by_pillar.items():
        lines.append(f"## {pillar} ({len(pillar_records)})")
        lines.append("")
        for record in sorted(pillar_records, key=lambda r: r.get("published", ""), reverse=True)[:25]:
            arxiv_short = record.get("arxiv_id", "").split("/abs/")[-1] or ""
            lines.append(
                f"- {record['title']} — [{arxiv_short}]({record.get('url', '')}) "
                f"({record.get('year', '')})"
            )
        lines.append("")

    lines.append("## Weekly digests")
    lines.append("")
    weekly_dir = data_root / "weekly"
    if weekly_dir.exists():
        for digest in sorted(weekly_dir.glob("*.md"), reverse=True):
            lines.append(f"- [{digest.name}](weekly/{digest.name})")
    path = data_root / "index.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def write_docs_landing(db: PaperDatabase, docs_root: Path) -> Path:
    """Regenerate the GitHub Pages landing page."""
    docs_root.mkdir(parents=True, exist_ok=True)
    stats = db.stats()
    records = db.recent(8)
    weekly_links = ""
    weekly_dir = docs_root.parent / "data" / "weekly"
    if weekly_dir.exists():
        digests = sorted(weekly_dir.glob("*.md"), reverse=True)[:4]
        weekly_links = "\n".join(
            f"- [Frontier AI Weekly {digest.stem}](https://github.com/pengpengyi92/p-research/blob/main/data/weekly/{digest.name})"
            for digest in digests
        )

    lines: list[str] = [
        "# 🌲 P-Research",
        "",
        "A self-updating, continuously running frontier-AI research intelligence.",
        "Weekly arXiv sweeps · living paper database · growing systematic survey.",
        "",
        f"**{stats['total_papers']} papers tracked** ({stats['verified_papers']} full-text verified) "
        f"across 6 pillars · last sweep {stats['newest_swept_on'][:10] or 'pending'}",
        "",
        "## Latest papers",
        "",
    ]
    for record in records:
        arxiv_short = record.get("arxiv_id", "").split("/abs/")[-1] or ""
        lines.append(
            f"- **{record['title']}** ([{arxiv_short}]({record.get('url', '')})) — "
            f"{record.get('pillar', '')}"
        )
    lines.extend(
        [
            "",
            "## Weekly digests",
            "",
            weekly_links or "- (first sweep pending)",
            "",
            "## Publications",
            "",
            "- [PRDT: Research as a Quant Problem — system paper (draft)](papers/paper2-prdt-system.md)",
            "- [Agent-Native Trading Systems — Quant×AI paper (draft)](papers/paper3-quant-ai.md)",
            "- [Living survey draft](https://github.com/pengpengyi92/p-research/blob/main/data/survey/draft.md) · [PDF](https://raw.githubusercontent.com/pengpengyi92/p-research/main/data/survey/draft.pdf)",
            "",
            "## Deepresearch notes",
            "",
            "- [№1 RAG](research/2026-08-19-rag.md) · [№2 Memory](research/2026-08-19-memory.md)"
            " · [№3 Tool Use](research/2026-08-19-tool-use.md)"
            " · [№4 Planning](research/2026-08-19-planning.md)"
            " · [№5 Eval](research/2026-08-19-eval.md)",
            "",
            "## Tools",
            "",
            "- [Quant×AI evaluation harness](harness/README.md) — the missing risk layer for open"
            " trading agents (Paper 3 §6) · cohort: [disciplined 4/4](harness/sample-disciplined.md)"
            " · [dsh-quant 4/4](harness/sample-dsh-quant.md) · [backtrader 4/4](harness/sample-backtrader.md)"
            " · [freqtrade 3/4](harness/sample-freqtrade.md) · [reckless 0/4](harness/sample-reckless.md)"
            " on the bundled public SPX fixture",
            "",
            "## Repository",
            "",
            "- [Source & methodology](https://github.com/pengpengyi92/p-research)",
            "- [Paper database](https://raw.githubusercontent.com/pengpengyi92/p-research/main/data/papers.jsonl)",
            "- [Survey outline](https://github.com/pengpengyi92/p-research/blob/main/data/survey/outline.md)",
        ]
    )
    path = docs_root / "index.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def write_survey_outline(db: PaperDatabase, survey_root: Path) -> Path:
    """Keep the survey skeleton in sync with the database."""
    survey_root.mkdir(parents=True, exist_ok=True)
    stats = db.stats()
    total = stats["total_papers"]
    counter = Counter(record.get("pillar", "?") for record in db.load())
    lines: list[str] = [
        "# Frontier AI — Living Survey Outline",
        "",
        "> Working title: *The Compute-Allocation Frontier: A Living, Reproducible "
        "Survey of LLM Reasoning and Test-Time Compute*",
        f"> Status: evidence-accumulating (v0.4). {total} papers in corpus, "
        f"{stats['verified_papers']} full-text verified.",
        "",
        "## Section progress",
        "",
        "- [x] §1 Introduction — drafted (`sections/01-introduction.md`)",
        "- [x] §2 Method — drafted (`sections/02-method.md`)",
        "- [x] §3 Foundations: CoT -> RLVR — drafted (`sections/03-foundations.md`)",
        "- [x] §4 Test-Time Compute — drafted (`sections/04-test-time-compute.md`)",
        "- [x] §5 Cross-Pillar Convergence — drafted (`sections/05-cross-pillar.md`)",
        "- [x] §6 Empirical Trends — drafted (`sections/06-empirical-trends.md`)",
        "- [x] §7 Open Problems — drafted (`sections/07-open-problems.md`)",
        "- [x] Full draft assembled (`draft.md` via `presearch assemble`)",
        "- [x] Automated citation audit (`presearch audit`, `audit-report.md`) — 0 FAIL",
        "- [ ] Hostile human review (>= 2 reviewers) + arXiv submission prep",
        "",
        "## Inclusion criteria (corpus v0.2)",
        "- Published on arXiv 2023-01-01 or later, primary category in the six pillar scopes.",
        "- Retrieved by the deterministic pillar queries; records are abstract-level until full-text verified.",
        "- Records are append-only and deduplicated by arXiv id; retractions or withdrawn papers are excluded during weekly re-verification.",
        "- A paper may enter the *core corpus* (citable claims) only after full-text verification (M2 gate).",
        "",
        "## 1. Introduction",
        "- [ ] The train-time -> test-time compute shift; why a living survey now.",
        "",
        "## 2. Method: A Reproducible, Continuously-Updating Corpus Pipeline",
        "- [ ] Six-pillar taxonomy, arXiv queries, deterministic structuring",
        "- [ ] Append-only `data/papers.jsonl` and the evidence chain",
        "",
        "## 3. Foundations: From Chain-of-Thought to RLVR",
        "- [ ] Verifiable rewards, GRPO/PPO, reward hacking",
        "",
        "## 4. Test-Time Compute",
        "- [ ] Search (MCTS/beam), verifiers & PRMs",
        "- [ ] Inference-time scaling laws and budget allocation",
        "",
        "## 5. Cross-Pillar Convergence under a Compute-Allocation Lens",
        "",
    ]
    for pillar in load_pillars(survey_root.parent / "presearch_pillars.json"):
        lines.append(f"- [ ] {pillar} — {counter.get(pillar, 0)} papers")
    lines.extend(
        [
            "",
            "## 6. Empirical Trends from the Living Corpus",
            "- [ ] Method migration, benchmark saturation, convergence clusters",
            "",
            "## 7. Open Problems, Risks, and Outlook",
            "- [ ] Verifier quality, compute budgets, safety, reproducibility",
            "",
            "---",
            "_Every section claim must cite paper records from `data/papers.jsonl`._",
        ]
    )
    path = survey_root / "outline.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path
